### ISSUE TITLE
how to set badge color ?

### ISSUE THREAD

**Issue by PaolinoAngeletti** [v2rc/Badger#1]
if i use paint.setColor(X) it change the border color. i want to set the entire badge color. how can i do this ?

**Comment by tynn** [comment]
Are you looking at the example [`CustomBadgeShape`](https://github.com/v2rc/Badger/blob/master/example/src/main/java/berlin/volders/badger/example/CustomBadgeShape.java#L43)?
Because this is only the border color for the custom shape.
In most cases you'd just use a simple `BadgeShape` and control the color with a `BadgeDrawable ` implementation like `CountBadge `.

**Comment by PaolinoAngeletti** [comment]
currently i'm using this code:
`return new CountBadge.Factory(context, new MPBadgeView(context, SCALE_FACTOR, GRAVITY));`
you're telling i've to use a code-like this?
`return new CountBadge.Factory(context, new BadgeShape(context, SCALE_FACTOR, GRAVITY) {
            @Override
            protected void onDraw(Canvas canvas, Rect region, Paint paint) {
                paint.setColor(Color.RED)
            }
        });`

**Comment by tynn** [comment]
I don't know how you implemented `MPBadgeView`.

But most likely `new CountBadge.Factory(new BadgeShape(context, SCALE_FACTOR, GRAVITY), Color.RED, aTextColor)` might be working for you. The `aTextColor` you'd have to define as well. The `badgeTextColor(Context)` is not public.

**Comment by PaolinoAngeletti** [comment]
yes, graet! your solution solved my problems! thanks again.
PS. very interesting library.
