### ISSUE TITLE
How to Change the badge factory dynamically?

### ISSUE THREAD

**Issue by Mohamed-Effat** [v2rc/Badger#3]
I'm trying to change the factory of the badge to increase it's size if the text goes beyond certain number of digits, in other words:
if the `countBadge.getText().length() > 3`
then change the factory to oval
what I've tried to do

first time setting up the badge:
```
CountBadge.Factory circleFactory =new CountBadge.Factory(this,
                BadgeShape.circle(.4f, Gravity.END | Gravity.TOP));
Badger.sett(imageView, coloredFactory);
```

and then in the imageView `onClickListener`

```
CountBadge badge = Badger.sett(imageView, null);
 if(badge.getText().length() > 3){
                    CountBadge.Factory ovalFactory = new CountBadge.Factory(
                            BadgeShape.oval(1f, 2f, Gravity.BOTTOM ),
                            Color.WHITE,
                            Color.BLACK);
                    badge = Badger.sett((ImageView) view, ovalFactory);
                }
```

but nothing changes when the new oval factory is used

**Comment by tynn** [comment]
The badge is [being reused](https://github.com/v2rc/Badger/blob/master/library/src/main/java/berlin/volders/badger/Badger.java#L63). That's why I'd suggest to create your own badge and shape which handles this use-case properly. Maybe provide a delegate `BadgeShape` which you can use to switch between two implementations. You'd have to keep the reference though. Would this work for you?
